$dbd_oracle_mm_opts = {
  "LIBS" => [
    "-LC:/Users/anand/.cpanm/work/1758302757.21496/DBD-Oracle-1.90 -loci"
  ],
  "DEFINE" => " -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\\"9.2.0.4.0\\\"",
  "VERSION_FROM" => "lib/DBD/Oracle.pm",
  "META_MERGE" => {
    "configure_requires" => {
      "DBI" => "1.623"
    },
    "build_requires" => {
      "ExtUtils::MakeMaker" => 0,
      "DBI" => "1.623",
      "Test::Simple" => "0.90"
    }
  },
  "OBJECT" => "\$(O_FILES)",
  "LICENSE" => "perl",
  "clean" => {
    "FILES" => "xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def mk.pm DBD_ORA_OBJ.*"
  },
  "PREREQ_PM" => {
    "DBI" => "1.623"
  },
  "AUTHOR" => "Tim Bunce (dbi-users\@perl.org)",
  "INC" => "-IC:/oracle/instantclient_23_9/sdk/include -IC:/oracle/instantclient_23_9/rdbms/demo -IC:\\Strawberry\\perl\\vendor\\lib\\auto\\DBI",
  "dist" => {
    "PREOP" => "\$(MAKE) -f Makefile.old distdir",
    "DIST_DEFAULT" => "clean distcheck disttest tardist",
    "SUFFIX" => "gz",
    "COMPRESS" => "gzip -v9"
  },
  "ABSTRACT_FROM" => "lib/DBD/Oracle.pm",
  "DIR" => [],
  "NAME" => "DBD::Oracle"
};
$dbd_oracle_mm_self = bless( {
  "MAN1SECTION" => 1,
  "FULL_AR" => "",
  "DIR" => [],
  "ABSTRACT_FROM" => "lib/DBD/Oracle.pm",
  "SHAR" => "shar",
  "DIRFILESEP" => "/",
  "COMPRESS" => "gzip --best",
  "TEST_F" => "\$(ABSPERLRUN) -MExtUtils::Command -e test_f --",
  "AR" => "ar",
  "VERSION" => "1.90",
  "TAR" => "tar",
  "DESTINSTALLSITEARCH" => "\$(DESTDIR)\$(INSTALLSITEARCH)",
  "PM" => {
    "lib/DBD/Oracle/Troubleshooting.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting.pod",
    "lib/DBD/Oracle/Troubleshooting/Win64.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting\\Win64.pod",
    "lib/DBD/Oracle/Troubleshooting/Cygwin.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting\\Cygwin.pod",
    "lib/DBD/Oracle/Troubleshooting/Hpux.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting\\Hpux.pod",
    "lib/DBD/Oracle/Troubleshooting/Linux.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting\\Linux.pod",
    "lib/DBD/Oracle/Object.pm" => "blib\\lib\\DBD\\Oracle\\Object.pm",
    "lib/DBD/Oracle/Troubleshooting/Macos.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting\\Macos.pod",
    "lib/DBD/Oracle/GetInfo.pm" => "blib\\lib\\DBD\\Oracle\\GetInfo.pm",
    "lib/DBD/Oracle/Troubleshooting/Vms.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting\\Vms.pod",
    "lib/DBD/Oracle.pm" => "blib\\lib\\DBD\\Oracle.pm",
    "lib/DBD/Oracle/Troubleshooting/Sun.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting\\Sun.pod",
    "lib/DBD/Oracle/Troubleshooting/Win32.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting\\Win32.pod",
    "mk.pm" => "\$(INST_LIB)\\DBD\\mk.pm",
    "lib/DBD/Oracle/Troubleshooting/Aix.pod" => "blib\\lib\\DBD\\Oracle\\Troubleshooting\\Aix.pod"
  },
  "TOUCH" => "\$(ABSPERLRUN) -MExtUtils::Command -e touch --",
  "MAKEMAKER" => "C:/Strawberry/perl/lib/ExtUtils/MakeMaker.pm",
  "XS_VERSION_MACRO" => "XS_VERSION",
  "MM_Win32_VERSION" => "7.76",
  "WARN_IF_OLD_PACKLIST" => "\$(ABSPERLRUN) -MExtUtils::Command::MM -e warn_if_old_packlist --",
  "PL_FILES" => {},
  "CP_NONEMPTY" => "\$(ABSPERLRUN) -MExtUtils::Command::MM -e cp_nonempty --",
  "BSLOADLIBS" => "",
  "CONFIG" => [
    "ar",
    "cc",
    "cccdlflags",
    "ccdlflags",
    "cpprun",
    "dlext",
    "dlsrc",
    "exe_ext",
    "full_ar",
    "ld",
    "lddlflags",
    "ldflags",
    "libc",
    "lib_ext",
    "obj_ext",
    "osname",
    "osvers",
    "ranlib",
    "sitelibexp",
    "sitearchexp",
    "so",
    "vendorarchexp",
    "vendorlibexp"
  ],
  "SO" => "dll",
  "ABSPERLRUNINST" => "\$(ABSPERLRUN) \"-I\$(INST_ARCHLIB)\" \"-I\$(INST_LIB)\"",
  "PERL_ARCHIVE" => "\$(PERL_INC)\\libperl542.a",
  "EXE_EXT" => ".exe",
  "PERL_ARCHIVEDEP" => "\$(PERL_INCDEP)\\libperl542.a",
  "DESTINSTALLVENDORMAN1DIR" => "\$(DESTDIR)\$(INSTALLVENDORMAN1DIR)",
  "USEMAKEFILE" => "-f",
  "dist" => {},
  "PERL_LIB" => "C:\\STRAWB~1\\perl\\lib",
  "MM_VERSION" => "7.76",
  "INST_LIBDIR" => "\$(INST_LIB)\\DBD",
  "EQUALIZE_TIMESTAMP" => "\$(ABSPERLRUN) -MExtUtils::Command -e eqtime --",
  "INSTALLVENDORSCRIPT" => "C:\\STRAWB~1\\perl\\bin",
  "DIST_CP" => "best",
  "LICENSE" => "perl",
  "PERM_DIR" => 755,
  "ZIPFLAGS" => "-r",
  "MACROSTART" => "",
  "MAN1EXT" => 1,
  "DESTINSTALLSCRIPT" => "\$(DESTDIR)\$(INSTALLSCRIPT)",
  "INSTALLDIRS" => "site",
  "PARENT_NAME" => "DBD",
  "FULLPERLRUN" => "\$(FULLPERL)",
  "SKIPHASH" => {},
  "INSTALLVENDORLIB" => "C:\\STRAWB~1\\perl\\vendor\\lib",
  "PERL_ARCHLIB" => "C:\\STRAWB~1\\perl\\lib",
  "DESTINSTALLMAN3DIR" => "\$(DESTDIR)\$(INSTALLMAN3DIR)",
  "DESTINSTALLVENDORARCH" => "\$(DESTDIR)\$(INSTALLVENDORARCH)",
  "BUILD_REQUIRES" => {},
  "PERL_ARCHLIBDEP" => "C:\\STRAWB~1\\perl\\lib",
  "MAKEFILE_OLD" => "Makefile.old",
  "BASEEXT" => "Oracle",
  "INSTALLSITEMAN1DIR" => "\$(INSTALLMAN1DIR)",
  "TEST_REQUIRES" => {},
  "RESULT" => [
    "# This Makefile is for the DBD::Oracle extension to perl.\n#\n# It was generated automatically by MakeMaker version\n# 7.76 (Revision: 77600) from the contents of\n# Makefile.PL. Don't edit this file, edit Makefile.PL instead.\n#\n#       ANY CHANGES MADE HERE WILL BE LOST!\n#\n#   MakeMaker ARGV: ()\n#\n",
    "#   MakeMaker Parameters:\n",
    "#     ABSTRACT_FROM => q[lib/DBD/Oracle.pm]",
    "#     AUTHOR => [q[Tim Bunce (dbi-users\@perl.org)]]",
    "#     BUILD_REQUIRES => {  }",
    "#     CONFIGURE_REQUIRES => {  }",
    "#     DEFINE => q[ -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\\"9.2.0.4.0\\\"]",
    "#     DIR => []",
    "#     INC => q[-IC:/oracle/instantclient_23_9/sdk/include -IC:/oracle/instantclient_23_9/rdbms/demo -IC:\\Strawberry\\perl\\vendor\\lib\\auto\\DBI]",
    "#     LIBS => [q[-LC:/Users/anand/.cpanm/work/1758302757.21496/DBD-Oracle-1.90 -loci]]",
    "#     LICENSE => q[perl]",
    "#     META_MERGE => { build_requires=>{ DBI=>q[1.623], ExtUtils::MakeMaker=>q[0], Test::Simple=>q[0.90] }, configure_requires=>{ DBI=>q[1.623] } }",
    "#     NAME => q[DBD::Oracle]",
    "#     OBJECT => q[\$(O_FILES)]",
    "#     PREREQ_PM => { DBI=>q[1.623] }",
    "#     TEST_REQUIRES => {  }",
    "#     VERSION_FROM => q[lib/DBD/Oracle.pm]",
    "#     clean => { FILES=>q[xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def mk.pm DBD_ORA_OBJ.*] }",
    "#     dist => { COMPRESS=>q[gzip -v9], DIST_DEFAULT=>q[clean distcheck disttest tardist], PREOP=>q[\$(MAKE) -f Makefile.old distdir], SUFFIX=>q[gz] }",
    "\n# --- MakeMaker post_initialize section:"
  ],
  "ABSPERL" => "\$(PERL)",
  "DESTINSTALLSITEMAN1DIR" => "\$(DESTDIR)\$(INSTALLSITEMAN1DIR)",
  "INST_AUTODIR" => "\$(INST_LIB)\\auto\\\$(FULLEXT)",
  "LD" => "g++",
  "NOOP" => "rem",
  "INSTALLMAN3DIR" => "none",
  "INST_LIB" => "blib\\lib",
  "DISTVNAME" => "DBD-Oracle-1.90",
  "PERL" => "\"C:\\Strawberry\\perl\\bin\\perl.exe\"",
  "VENDORPREFIX" => "C:\\STRAWB~1\\perl\\vendor",
  "LD_RUN_PATH" => "",
  "LDFLAGS" => "-s -L\"C:\\STRAWB~1\\perl\\lib\\CORE\" -L\"C:\\STRAWB~1\\c\\lib\" -L\"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\" -L\"C:\\STRAWB~1\\c\\lib\\gcc\\x86_64-w64-mingw32\\13.2.0\"",
  "LIBS" => [],
  "TARFLAGS" => "cvf",
  "DISTNAME" => "DBD-Oracle",
  "INSTALLVENDORMAN3DIR" => "\$(INSTALLMAN3DIR)",
  "PERL_INCDEP" => "C:\\STRAWB~1\\perl\\lib\\CORE",
  "INST_DYNAMIC" => "\$(INST_ARCHAUTODIR)\\\$(DLBASE).\$(DLEXT)",
  "PERM_RW" => 644,
  "INST_BOOT" => "\$(INST_ARCHAUTODIR)\\\$(BASEEXT).bs",
  "DESTINSTALLSITEBIN" => "\$(DESTDIR)\$(INSTALLSITEBIN)",
  "MACROEND" => "",
  "INST_SCRIPT" => "blib\\script",
  "LIB_EXT" => ".a",
  "RCS_LABEL" => "rcs -Nv\$(VERSION_SYM): -q",
  "INST_ARCHLIB" => "blib\\arch",
  "CCDLFLAGS" => " ",
  "TRUE" => "\$(ABSPERLRUN)  -e \"exit 0\" --",
  "DOC_INSTALL" => "\$(ABSPERLRUN) -MExtUtils::Command::MM -e perllocal_install --",
  "RM_F" => "\$(ABSPERLRUN) -MExtUtils::Command -e rm_f --",
  "EXPORT_LIST" => "\$(BASEEXT).def",
  "NAME" => "DBD::Oracle",
  "FULLPERLRUNINST" => "\$(FULLPERLRUN) \"-I\$(INST_ARCHLIB)\" \"-I\$(INST_LIB)\"",
  "PERLRUNINST" => "\$(PERLRUN) \"-I\$(INST_ARCHLIB)\" \"-I\$(INST_LIB)\"",
  "CHMOD" => "\$(ABSPERLRUN) -MExtUtils::Command -e chmod --",
  "DIST_DEFAULT" => "tardist",
  "DESTINSTALLARCHLIB" => "\$(DESTDIR)\$(INSTALLARCHLIB)",
  "PREFIX" => "\$(SITEPREFIX)",
  "INST_BIN" => "blib\\bin",
  "FIRST_MAKEFILE" => "Makefile",
  "INSTALLVENDORARCH" => "C:\\STRAWB~1\\perl\\vendor\\lib",
  "ZIP" => "zip",
  "DESTINSTALLSITEMAN3DIR" => "\$(DESTDIR)\$(INSTALLSITEMAN3DIR)",
  "INSTALLMAN1DIR" => "none",
  "DEFINE_VERSION" => "-D\$(VERSION_MACRO)=\\\"\$(VERSION)\\\"",
  "CC" => "gcc",
  "MAN3PODS" => {},
  "UMASK_NULL" => "umask 0",
  "INSTALLARCHLIB" => "C:\\STRAWB~1\\perl\\lib",
  "LDDLFLAGS" => "-shared -s -L\"C:\\STRAWB~1\\perl\\lib\\CORE\" -L\"C:\\STRAWB~1\\c\\lib\" -L\"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\" -L\"C:\\STRAWB~1\\c\\lib\\gcc\\x86_64-w64-mingw32\\13.2.0\"",
  "DESTINSTALLBIN" => "\$(DESTDIR)\$(INSTALLBIN)",
  "TEST_S" => "\$(ABSPERLRUN) -MExtUtils::Command::MM -e test_s --",
  "PERL_INC" => "C:\\STRAWB~1\\perl\\lib\\CORE",
  "FALSE" => "\$(ABSPERLRUN)  -e \"exit 1\" --",
  "HAS_LINK_CODE" => 1,
  "DESTINSTALLSITESCRIPT" => "\$(DESTDIR)\$(INSTALLSITESCRIPT)",
  "DESTINSTALLVENDORLIB" => "\$(DESTDIR)\$(INSTALLVENDORLIB)",
  "MAKE_APERL_FILE" => "Makefile.aperl",
  "DESTINSTALLSITELIB" => "\$(DESTDIR)\$(INSTALLSITELIB)",
  "XS_DEFINE_VERSION" => "-D\$(XS_VERSION_MACRO)=\\\"\$(XS_VERSION)\\\"",
  "MAP_TARGET" => "perl",
  "CCCDLFLAGS" => " ",
  "DESTINSTALLPRIVLIB" => "\$(DESTDIR)\$(INSTALLPRIVLIB)",
  "DESTINSTALLVENDORSCRIPT" => "\$(DESTDIR)\$(INSTALLVENDORSCRIPT)",
  "INSTALLSITELIB" => "C:\\STRAWB~1\\perl\\site\\lib",
  "SITEPREFIX" => "C:\\STRAWB~1\\perl\\site",
  "VERSION_MACRO" => "VERSION",
  "PREREQ_PM" => {
    "DBI" => "1.623"
  },
  "OBJECT" => "\$(O_FILES)",
  "clean" => {},
  "INST_ARCHLIBDIR" => "\$(INST_ARCHLIB)\\DBD",
  "ECHO" => "\$(ABSPERLRUN) -l -e \"binmode STDOUT, qq{:raw}; print qq{\@ARGV}\" --",
  "RM_RF" => "\$(ABSPERLRUN) -MExtUtils::Command -e rm_rf --",
  "CPPRUN" => "gcc -E",
  "UNINST" => 0,
  "INSTALLSITEMAN3DIR" => "\$(INSTALLMAN3DIR)",
  "MAN3EXT" => 3,
  "DESTINSTALLMAN1DIR" => "\$(DESTDIR)\$(INSTALLMAN1DIR)",
  "EXTRALIBS" => "\"liboci.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libmoldname.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libkernel32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libuser32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libgdi32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libwinspool.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libcomdlg32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libadvapi32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libshell32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libole32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\liboleaut32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libnetapi32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libuuid.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libws2_32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libmpr.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libwinmm.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libversion.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libodbc32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libodbccp32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libcomctl32.a\"",
  "INSTALLSITESCRIPT" => "C:\\STRAWB~1\\perl\\site\\bin",
  "PERLRUN" => "\$(PERL)",
  "DEFINE" => " -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\\"9.2.0.4.0\\\"",
  "INST_MAN1DIR" => "blib\\man1",
  "MM_REVISION" => 77600,
  "CP" => "\$(ABSPERLRUN) -MExtUtils::Command -e cp --",
  "DLSRC" => "dl_win32.xs",
  "PERM_RWX" => 755,
  "OSVERS" => "10.0.26100.4652",
  "INST_MAN3DIR" => "blib\\man3",
  "INC" => "-IC:/oracle/instantclient_23_9/sdk/include -IC:/oracle/instantclient_23_9/rdbms/demo -IC:\\Strawberry\\perl\\vendor\\lib\\auto\\DBI",
  "MKPATH" => "\$(ABSPERLRUN) -MExtUtils::Command -e mkpath --",
  "SITELIBEXP" => "C:\\STRAWB~1\\perl\\site\\lib",
  "MAKEFILE" => "Makefile",
  "NAME_SYM" => "DBD_Oracle",
  "DLEXT" => "xs.dll",
  "VERSION_SYM" => "1_90",
  "PERLPREFIX" => "C:\\STRAWB~1\\perl",
  "OSNAME" => "MSWin32",
  "PMLIBPARENTDIRS" => [
    "lib"
  ],
  "NOECHO" => "\@",
  "H" => [
    "Oracle.h",
    "dbdimp.h",
    "dbivport.h",
    "ocitrace.h"
  ],
  "OBJ_EXT" => ".o",
  "PREOP" => "\$(NOECHO) \$(NOOP)",
  "MAN3SECTION" => 3,
  "VERSION_FROM" => "lib/DBD/Oracle.pm",
  "VERBINST" => 0,
  "SITEARCHEXP" => "C:\\STRAWB~1\\perl\\site\\lib",
  "PMLIBDIRS" => [
    "lib"
  ],
  "PERLMAINCC" => "\$(CC)",
  "PERL_SRC" => undef,
  "MV" => "\$(ABSPERLRUN) -MExtUtils::Command -e mv --",
  "FULLPERL" => "\"C:\\Strawberry\\perl\\bin\\perl.exe\"",
  "PERL_CORE" => 0,
  "FULLEXT" => "DBD\\Oracle",
  "DESTDIR" => "",
  "MAKE" => "gmake",
  "MOD_INSTALL" => "\$(ABSPERLRUN) -MExtUtils::Install -e \"install([ from_to => {\@ARGV}, verbose => '\$(VERBINST)', uninstall_shadows => '\$(UNINST)', dir_mode => '\$(PERM_DIR)' ]);\" --",
  "UNINSTALL" => "\$(ABSPERLRUN) -MExtUtils::Command::MM -e uninstall --",
  "XS_VERSION" => "1.90",
  "ABSPERLRUN" => "\$(ABSPERL)",
  "XS" => {
    "Oracle.xs" => "Oracle.c"
  },
  "DESTINSTALLVENDORMAN3DIR" => "\$(DESTDIR)\$(INSTALLVENDORMAN3DIR)",
  "LDFROM" => "\$(OBJECT)",
  "PERL_ARCHIVE_AFTER" => "",
  "INSTALLVENDORMAN1DIR" => "\$(INSTALLMAN1DIR)",
  "INSTALLPRIVLIB" => "C:\\STRAWB~1\\perl\\lib",
  "LIBC" => "-lucrt",
  "INSTALLBIN" => "C:\\STRAWB~1\\perl\\bin",
  "MAN1PODS" => {},
  "INST_STATIC" => "\$(INST_ARCHAUTODIR)\\\$(BASEEXT)\$(LIB_EXT)",
  "LDLOADLIBS" => "\"liboci.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libmoldname.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libkernel32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libuser32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libgdi32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libwinspool.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libcomdlg32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libadvapi32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libshell32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libole32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\liboleaut32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libnetapi32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libuuid.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libws2_32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libmpr.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libwinmm.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libversion.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libodbc32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libodbccp32.a\" \"C:\\STRAWB~1\\c\\x86_64-w64-mingw32\\lib\\libcomctl32.a\"",
  "TO_UNIX" => "\$(NOECHO) \$(NOOP)",
  "INSTALLSITEBIN" => "C:\\STRAWB~1\\perl\\site\\bin",
  "INSTALLVENDORBIN" => "C:\\STRAWB~1\\perl\\bin",
  "ABSTRACT" => "Oracle database driver for the DBI module",
  "DESTINSTALLVENDORBIN" => "\$(DESTDIR)\$(INSTALLVENDORBIN)",
  "SUFFIX" => ".gz",
  "CI" => "ci -u",
  "BOOTDEP" => "",
  "ECHO_N" => "\$(ABSPERLRUN)  -e \"print qq{\@ARGV}\" --",
  "FIXIN" => "pl2bat.bat",
  "C" => [
    "Oracle.c",
    "dbdcnx.c",
    "dbdimp.c",
    "oci8.c"
  ],
  "LINKTYPE" => "dynamic",
  "DEV_NULL" => "> NUL",
  "DLBASE" => "\$(BASEEXT)",
  "INSTALLSITEARCH" => "C:\\STRAWB~1\\perl\\site\\lib",
  "RANLIB" => "rem",
  "POSTOP" => "\$(NOECHO) \$(NOOP)",
  "LIBPERL_A" => "libperl.a",
  "INST_ARCHAUTODIR" => "\$(INST_ARCHLIB)\\auto\\\$(FULLEXT)",
  "INSTALLSCRIPT" => "C:\\STRAWB~1\\perl\\bin",
  "CONFIGURE_REQUIRES" => {},
  "AUTHOR" => [
    "Tim Bunce (dbi-users\@perl.org)"
  ],
  "VENDORLIBEXP" => "C:\\STRAWB~1\\perl\\vendor\\lib",
  "ARGS" => {
    "LIBS" => [],
    "DEFINE" => " -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\\"9.2.0.4.0\\\"",
    "VERSION_FROM" => "lib/DBD/Oracle.pm",
    "META_MERGE" => {},
    "OBJECT" => "\$(O_FILES)",
    "LICENSE" => "perl",
    "clean" => {},
    "PREREQ_PM" => {},
    "AUTHOR" => [],
    "INC" => "-IC:/oracle/instantclient_23_9/sdk/include -IC:/oracle/instantclient_23_9/rdbms/demo -IC:\\Strawberry\\perl\\vendor\\lib\\auto\\DBI",
    "dist" => {},
    "ABSTRACT_FROM" => "lib/DBD/Oracle.pm",
    "DIR" => [],
    "NAME" => "DBD::Oracle"
  },
  "META_MERGE" => {},
  "O_FILES" => [
    "Oracle.o",
    "dbdcnx.o",
    "dbdimp.o",
    "oci8.o"
  ],
  "AR_STATIC_ARGS" => "cr",
  "VENDORARCHEXP" => "C:\\STRAWB~1\\perl\\vendor\\lib"
}, 'PACK001' );
$dbd_oracle_mm_self->{"DIR"} = $dbd_oracle_mm_opts->{"DIR"};
$dbd_oracle_mm_self->{"dist"} = $dbd_oracle_mm_opts->{"dist"};
$dbd_oracle_mm_self->{"LIBS"} = $dbd_oracle_mm_opts->{"LIBS"};
$dbd_oracle_mm_self->{"clean"} = $dbd_oracle_mm_opts->{"clean"};
$dbd_oracle_mm_self->{"ARGS"}{"LIBS"} = $dbd_oracle_mm_opts->{"LIBS"};
$dbd_oracle_mm_self->{"ARGS"}{"META_MERGE"} = $dbd_oracle_mm_opts->{"META_MERGE"};
$dbd_oracle_mm_self->{"ARGS"}{"clean"} = $dbd_oracle_mm_opts->{"clean"};
$dbd_oracle_mm_self->{"ARGS"}{"PREREQ_PM"} = $dbd_oracle_mm_opts->{"PREREQ_PM"};
$dbd_oracle_mm_self->{"ARGS"}{"AUTHOR"} = $dbd_oracle_mm_self->{"AUTHOR"};
$dbd_oracle_mm_self->{"ARGS"}{"dist"} = $dbd_oracle_mm_opts->{"dist"};
$dbd_oracle_mm_self->{"ARGS"}{"DIR"} = $dbd_oracle_mm_opts->{"DIR"};
$dbd_oracle_mm_self->{"META_MERGE"} = $dbd_oracle_mm_opts->{"META_MERGE"};
